name: Deploy (production)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  checks: write
  deployments: write
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy
    uses: primer/.github/.github/workflows/deploy.yml@v1.0.0
    with:
      node_version: 16
      install: yarn
      build: yarn build
      output_dir: build
