name: Deploy (preview)

on:
  pull_request:

permissions:
  contents: read
  checks: write
  deployments: write
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.repository == 'primer/prism' }}
    name: Deploy
    uses: primer/.github/.github/workflows/deploy_preview.yml@v1.0.0
    with:
      node_version: 16
      install: yarn
      build: yarn build:preview
      output_dir: build
